import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ProjectsProvider } from "@/context/ProjectsContext";
import Link from "next/link";


const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
		>
			<ProjectsProvider>
				<body className="min-h-full max-w-[1280px] m-auto">
					<header className="flex justify-between">
						<Link href="/">Task Manager</Link>
						<div className="flex gap-8">
							<input placeholder="Search..." />
							<div className="flex gap-4">
								<button className="pointer">Settings</button>
								<button className="pointer">Profile</button>
							</div>
						</div>
					</header>
					<aside className="flex flex-col items-start my-4">
						<Link href="/">Dashboard</Link>
						<Link href="/projects/">Projects</Link>
						<Link href="/tasks/">Tasks</Link>
					</aside>
					{children}
					<footer>
						<p>This is the footer</p>
					</footer>
				</body>
			</ProjectsProvider>
		</html>
	);
}
